import os
from datetime import datetime

def generate_report(detection_result, location, traffic_result=None):
    
    # Current timestamp
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    report_id = datetime.now().strftime("%Y%m%d%H%M%S")
    
    # Build report content
    report = f"""
╔══════════════════════════════════════════════════════════╗
         SMARTROAD AI - CIVIC COMPLAINT REPORT
╚══════════════════════════════════════════════════════════╝

Report ID     : SR-{report_id}
Generated At  : {timestamp}
Location      : {location}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                    ROAD DAMAGE ANALYSIS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Damage Found      : {'YES ⚠️' if detection_result['damage_found'] else 'NO ✅'}
Total Detections  : {detection_result['total_detections']}

"""

    # Add individual detections
    if detection_result['damage_found']:
        report += "Damage Details:\n"
        report += "-" * 50 + "\n"
        
        for i, detection in enumerate(detection_result['detections'], 1):
            report += f"""
  [{i}] Type       : {detection['class'].upper()}
       Confidence : {detection['confidence']}%
       Severity   : {detection['severity']}
"""
        
        # Overall severity
        severities = [d['severity'] for d in detection_result['detections']]
        if 'High' in severities:
            overall = 'HIGH - Immediate attention required'
        elif 'Medium' in severities:
            overall = 'MEDIUM - Repair needed soon'
        else:
            overall = 'LOW - Monitor regularly'
            
        report += f"\nOverall Severity  : {overall}\n"

    else:
        report += "✅ No road damage detected in this image.\n"

    # Add traffic section if provided
    if traffic_result:
        report += f"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                   TRAFFIC ANALYSIS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Area              : {traffic_result['area'].title()}
Time              : {traffic_result['time']}
Congestion Level  : {traffic_result['congestion_level']}
Suggestion        : {traffic_result['suggestion']}
Alternate Route   : {traffic_result['alternate_route']}
"""

    # Footer
    report += f"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
                      ACTION REQUIRED
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This report has been auto-generated by SmartRoad AI.
Please forward to the concerned Municipal Corporation
for immediate road repair action.

Reported Via  : SmartRoad AI System
Authority     : Municipal Corporation
Status        : PENDING ACTION

╔══════════════════════════════════════════════════════════╗
              END OF REPORT - SR-{report_id}
╚══════════════════════════════════════════════════════════╝
"""

    # Save report to file
    os.makedirs('reports', exist_ok=True)
    report_filename = f"reports/SR-{report_id}.txt"
    
    with open(report_filename, 'w', encoding='utf-8') as f:
        f.write(report)

    return {
        'report_id': f'SR-{report_id}',
        'report_content': report,
        'report_file': report_filename,
        'timestamp': timestamp,
        'location': location
    }